export const ADD = "ADD_STUDENT"
export const ADD_SUCCESS = "ADD_STUDENT_SUCCESS"
export const ADD_FAILED = "ADD_STUDENT_FAILED"

export const GET_ALL = 'GET_ALL_STUDENT';
export const GET_ALL_SUCCESS = 'GET_ALL_STUDENT_SUCCESS';
export const GET_ALL_FAILED = 'GET_ALL_STUDENT_FAILED';

